#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4.1 on Tue Nov 21 15:15:19 2006

import wx

class pwxUserImports(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: pwxUserImports.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.sizer_4_staticbox = wx.StaticBox(self, -1, "User Cases")
        self.sizer_5_staticbox = wx.StaticBox(self, -1, "User Model Files")
        self.sizer_6_staticbox = wx.StaticBox(self, -1, "Commands")
        self.sizer_2_staticbox = wx.StaticBox(self, -1, "User Names")
        self.list_box_user_names = wx.ListBox(self, -1, choices=[])
        self.list_box_user_cases = wx.ListBox(self, -1, choices=[])
        self.list_box_user_modelfiles = wx.ListBox(self, -1, choices=[])
        self.button_use_user = wx.Button(self, -1, "User Files")
        self.button_1 = wx.Button(self, -1, "Import Files")
        self.button_cancel = wx.Button(self, -1, "Cancel")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: pwxUserImports.__set_properties
        self.SetTitle("User Import")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: pwxUserImports.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_6 = wx.StaticBoxSizer(self.sizer_6_staticbox, wx.HORIZONTAL)
        sizer_5 = wx.StaticBoxSizer(self.sizer_5_staticbox, wx.HORIZONTAL)
        sizer_4 = wx.StaticBoxSizer(self.sizer_4_staticbox, wx.HORIZONTAL)
        sizer_2 = wx.StaticBoxSizer(self.sizer_2_staticbox, wx.VERTICAL)
        sizer_2.Add(self.list_box_user_names, 1, wx.ADJUST_MINSIZE, 0)
        sizer_1.Add(sizer_2, 0, wx.EXPAND, 1)
        sizer_4.Add(self.list_box_user_cases, 1, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_5.Add(self.list_box_user_modelfiles, 1, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        sizer_3.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_6.Add(self.button_use_user, 0, wx.ADJUST_MINSIZE, 0)
        sizer_6.Add(self.button_1, 0, wx.ADJUST_MINSIZE, 0)
        sizer_6.Add(self.button_cancel, 0, wx.ADJUST_MINSIZE, 0)
        sizer_3.Add(sizer_6, 0, wx.EXPAND, 0)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade
		self.master = None


	def SetMaster(self, master):
		self.master = master
# end of class pwxUserImports


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    dialog_1 = pwxUserImports(None, -1, "")
    app.SetTopWindow(dialog_1)
    dialog_1.Show()
    app.MainLoop()
